### ISSUE TITLE
I can't open main.java

### ISSUE THREAD

**Issue by g4269159** [kshitij1234/Anime-Downloader#1]
I don't really understand where should I open it... Which IDE should I use and how?

**Comment by kshitij1234** [comment]
I am sorry for the trouble . I meant to create an executable file for easy use but cant seem to get the time . I will create one as soon as I get the time . In the meantime, if you have followed all the steps above you can do 2 things - 

1) Can download Eclipse IDE from http://www.eclipse.org/downloads/packages/eclipse-ide-java-ee-developers/marsr , install it and go to File->Open Existing Project and navigate to where you have downloaded the source code and open up the project. After that open src/application/Main.java in the IDE and run it using the play button on the top.

2) Can use the command line to directly run the script . Navigate to the scripts folder using cmd and run the following command (I am only giving the command for animeheaven as the command for 9anime is a bit complicated) -

python -u AnimeHeavenDownloader.py "url of series inside quotes" "path where to download in quotes"

**Comment by g4269159** [comment]
I got it to work with your kind instructions, thank you! I'm still looking forward to testing out the executable when possible!
